In [1]:
import pandas as pd
import re
import numpy as np

 ## 讀csv

In [2]:
df = pd.read_csv("attraction_info_final.csv")
# df = df.drop("Unnamed: 0",axis="columns")
df.head(2)

,google_url,place_name,total_rating,place_category,total_reviews,cost,address,district,eat_in,to_go_1,...,New review,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,latitude,longitude
0,https://www.google.com.tw/maps/place/%E5%A4%A7...,大稻埕碼頭貨櫃市集,4.5,旅遊景點,1834.0,NaN,103台北市大同區,Plus Code: 3G44+FX 大同區 台北市,0,0,...,1001-2000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",23.546162,120.640213
1,https://www.google.com.tw/maps/place/%E9%97%9C...,關渡碼頭,4.3,渡輪碼頭,171.0,NaN,112台北市北投區,Plus Code: 4FC6+66 北投區 台北市,0,0,...,51-200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",23.546162,120.640213

## Add column ,name "New district"

In [3]:
df["New district"] = df["district"].str.split(" ").str.get(3)
df.head(2)

,google_url,place_name,total_rating,place_category,total_reviews,cost,address,district,eat_in,to_go_1,...,New review,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,latitude,longitude
0,https://www.google.com.tw/maps/place/%E5%A4%A7...,大稻埕碼頭貨櫃市集,4.5,旅遊景點,1834.0,NaN,103台北市大同區,Plus Code: 3G44+FX 大同區 台北市,0,0,...,1001-2000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",23.546162,120.640213
1,https://www.google.com.tw/maps/place/%E9%97%9C...,關渡碼頭,4.3,渡輪碼頭,171.0,NaN,112台北市北投區,Plus Code: 4FC6+66 北投區 台北市,0,0,...,51-200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",23.546162,120.640213

## Add column ,name "New Rating" ,define rating scope

In [4]:
df["New Rating"] = df["total_rating"].apply(lambda x : 1 if x<=1.5 else (2 if x<=2.5 else (3 if x<=3.5 else (4 if x<=4.5 else 5))))

In [5]:
df.head(2)

,google_url,place_name,total_rating,place_category,total_reviews,cost,address,district,eat_in,to_go_1,...,New review,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,latitude,longitude
0,https://www.google.com.tw/maps/place/%E5%A4%A7...,大稻埕碼頭貨櫃市集,4.5,旅遊景點,1834.0,NaN,103台北市大同區,Plus Code: 3G44+FX 大同區 台北市,0,0,...,1001-2000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",23.546162,120.640213
1,https://www.google.com.tw/maps/place/%E9%97%9C...,關渡碼頭,4.3,渡輪碼頭,171.0,NaN,112台北市北投區,Plus Code: 4FC6+66 北投區 台北市,0,0,...,51-200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",23.546162,120.640213

## Add column , name "New review", define review scope

In [6]:
df["New review"] = df["total_reviews"].apply(lambda x : "0-50" if x<=50 else ("51-200" if x<=200 else ("201-500" if x<=500 else ("501-1000" if x <=1000 else ("1001-2000" if x <= 2000 else ("2001-3000" if x <=3000 else "3001 up"))))))

In [7]:
df.head(2)

,google_url,place_name,total_rating,place_category,total_reviews,cost,address,district,eat_in,to_go_1,...,New review,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,latitude,longitude
0,https://www.google.com.tw/maps/place/%E5%A4%A7...,大稻埕碼頭貨櫃市集,4.5,旅遊景點,1834.0,NaN,103台北市大同區,Plus Code: 3G44+FX 大同區 台北市,0,0,...,1001-2000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",23.546162,120.640213
1,https://www.google.com.tw/maps/place/%E9%97%9C...,關渡碼頭,4.3,渡輪碼頭,171.0,NaN,112台北市北投區,Plus Code: 4FC6+66 北投區 台北市,0,0,...,51-200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",23.546162,120.640213

##  Add columns , name "opening_hours", define "Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"

In [8]:
df1 = df["opening_hour"].fillna(value="0、999:0 到 999:0;0、999:0 到 999:0;0、999:0 到 999:0;0、999:0 到 999:0;0、999:0 到 999:0;0、999:0 到 999:0;0、999:0 到 999:0")  # 下面切割用';',不補0;0 切割會報錯
df1.head(2)  # 第10row有Nan

0    星期三、16:00 到 00:00; 星期四、16:00 到 00:00; 星期五、16:0...
1    0、999:0 到 999:0;0、999:0 到 999:0;0、999:0 到 999:...
Name: opening_hour, dtype: object

In [9]:
# 原Series先用';'分割
pd.set_option("max_colwidth",999)
df1 = df1.str.split(';')
df1.head(2)

0    [星期三、16:00 到 00:00,  星期四、16:00 到 00:00,  星期五、16:00 到 00:00,  星期六、12:00 到 00:00,  星期日、12:00 到 00:00,  星期一、16:00 到 00:00,  星期二、16:00 到 00:00. 隱藏本週營業時間]
1                                  [0、999:0 到 999:0, 0、999:0 到 999:0, 0、999:0 到 999:0, 0、999:0 到 999:0, 0、999:0 到 999:0, 0、999:0 到 999:0, 0、999:0 到 999:0]
Name: opening_hour, dtype: object

In [10]:
def check_business_hours(week_list):
    
    # 宣告為tuple，避免被改值
    one  = (1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)
    zero = (0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
    
    # 宣告變數存相對應的字串
    str_monday    = str([s for s in week_list if "星期一" in s])
    str_tuesday   = str([s for s in week_list if "星期二" in s])
    str_wednesday = str([s for s in week_list if "星期三" in s])
    str_thursday  = str([s for s in week_list if "星期四" in s])
    str_friday    = str([s for s in week_list if "星期五" in s])
    str_saturday  = str([s for s in week_list if "星期六" in s])
    str_sunday    = str([s for s in week_list if "星期日" in s])
        
    str_week = [str_monday,str_tuesday,str_wednesday,str_thursday,str_friday,str_saturday,str_sunday]
    
    openHour_0_1_list =[]
    listt = []
    
    for day in str_week:
        
        time = re.sub(r':\d\d','',day)
        time = re.findall(r'\d\d', time)
        time = list(map(int, time)) #str轉int
        
        if len(time) == 0:
            listt = list(zero)
            
        elif len(time) == 1:
            listt = list(one)
    
        elif len(time) > 1:
            
            # 晚上營業時間沒有跨日
            if time[-1] - time[0] > 0:
                listt = list(zero)
                
                if len(time) >= 2:
                    listt[time[0]:time[1]] = np.ones(time[1]-time[0])

                    if len(time) >= 4:
                        listt[time[2]:time[3]] = np.ones(abs(time[3]-time[2]))

                        if len(time) >= 6:
                            listt[time[4]:time[5]] = np.ones(time[5]-time[4])

                            if len(time) >= 8:
                                listt[time[6]:time[7]] = np.ones(time[7]-time[6])
           
        
            # 晚上營業時間跨日    
            if time[-1] - time[0] < 0:
                listt = list(one)
                
                if len(time) >= 2:
                    listt[time[-1]:time[0]] = np.zeros(abs(time[-1]-time[0]))

                    if len(time) >= 4:
                        listt[time[1]:time[2]] = np.zeros(abs(time[2]-time[1]))

                        if len(time) >= 6:
                            listt[time[3]:time[4]] = np.zeros(abs(time[4]-time[3]))

                            if len(time) >= 8:
                                listt[time[5]:time[6]] = np.zeros(abs(time[6]-time[5]))
            
        openHour_0_1_list.append(listt)
    return openHour_0_1_list

In [11]:
monday_openList    = []
tuesday_openList   = []
wednesday_openList = []
thursday_openList  = []
friday_openList    = []
saturday_openList  = []
sunday_openList    = []

for i in range(len(df1)):
    list_ = check_business_hours(df1[i])
    monday_openList.append(list_[0])
    tuesday_openList.append(list_[1])
    wednesday_openList.append(list_[2])
    thursday_openList.append(list_[3])
    friday_openList.append(list_[4])
    saturday_openList.append(list_[5])
    sunday_openList.append(list_[6])

df["Monday"]    = pd.Series(monday_openList)
df["Tuesday"]   = pd.Series(tuesday_openList)
df["Wednesday"] = pd.Series(wednesday_openList)
df["Thursday"]  = pd.Series(thursday_openList)
df["Friday"]    = pd.Series(friday_openList)
df["Saturday"]  = pd.Series(saturday_openList)
df["Sunday"]    = pd.Series(sunday_openList)

In [12]:
df.head(2)

,google_url,place_name,total_rating,place_category,total_reviews,cost,address,district,eat_in,to_go_1,...,New review,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,latitude,longitude
0,"https://www.google.com.tw/maps/place/%E5%A4%A7%E7%A8%BB%E5%9F%95%E7%A2%BC%E9%A0%AD%E8%B2%A8%E6%AB%83%E5%B8%82%E9%9B%86/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442a91146436021:0x6dafa0aee6af38bf!8m2!3d25.0561339!4d121.5074245?hl=zh-TW",大稻埕碼頭貨櫃市集,4.5,旅遊景點,1834.0,NaN,103台北市大同區,Plus Code: 3G44+FX 大同區 台北市,0,0,...,1001-2000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",23.546162,120.640213
1,"https://www.google.com.tw/maps/place/%E9%97%9C%E6%B8%A1%E7%A2%BC%E9%A0%AD/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442af6e97a707ef:0xd2c2fd02bda75f14!8m2!3d25.1206151!4d121.4605922?hl=zh-TW",關渡碼頭,4.3,渡輪碼頭,171.0,NaN,112台北市北投區,Plus Code: 4FC6+66 北投區 台北市,0,0,...,51-200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",23.546162,120.640213

## Add columns "latitude" , "longitude"

In [13]:
df1 = df["google_url"].str.findall("\d{2,}\.\d*")
df1

0      [23.546162, 120.6402133, 25.0561339, 121.5074245]
1      [23.546162, 120.6402133, 25.1206151, 121.4605922]
2      [23.546162, 120.6402133, 25.0761837, 121.5374097]
3        [23.546162, 120.6402133, 25.125148, 121.461198]
4        [23.546162, 120.6402133, 25.099919, 121.528024]
                             ...
342                            [25.0975497, 121.5945882]
343                            [25.0374508, 121.5638224]
344                            [25.1134462, 121.5329249]
345                            [25.0830998, 121.6019904]
346                            [25.0650043, 121.5097477]
Name: google_url, Length: 347, dtype: object

In [14]:
df1 = df1.apply(pd.Series)
df1

              0            1           2            3
0     23.546162  120.6402133  25.0561339  121.5074245
1     23.546162  120.6402133  25.1206151  121.4605922
2     23.546162  120.6402133  25.0761837  121.5374097
3     23.546162  120.6402133   25.125148   121.461198
4     23.546162  120.6402133   25.099919   121.528024
..          ...          ...         ...          ...
342  25.0975497  121.5945882         NaN          NaN
343  25.0374508  121.5638224         NaN          NaN
344  25.1134462  121.5329249         NaN          NaN
345  25.0830998  121.6019904         NaN          NaN
346  25.0650043  121.5097477         NaN          NaN

[347 rows x 4 columns]

In [15]:
df["latitude"] = df1.loc[:,0]
df["longitude"] = df1.loc[:,1]

In [16]:
df

,google_url,place_name,total_rating,place_category,total_reviews,cost,address,district,eat_in,to_go_1,...,New review,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,latitude,longitude
0,"https://www.google.com.tw/maps/place/%E5%A4%A7%E7%A8%BB%E5%9F%95%E7%A2%BC%E9%A0%AD%E8%B2%A8%E6%AB%83%E5%B8%82%E9%9B%86/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442a91146436021:0x6dafa0aee6af38bf!8m2!3d25.0561339!4d121.5074245?hl=zh-TW",大稻埕碼頭貨櫃市集,4.5,旅遊景點,1834.0,NaN,103台北市大同區,Plus Code: 3G44+FX 大同區 台北市,0,0,...,1001-2000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",23.546162,120.6402133
1,"https://www.google.com.tw/maps/place/%E9%97%9C%E6%B8%A1%E7%A2%BC%E9%A0%AD/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442af6e97a707ef:0xd2c2fd02bda75f14!8m2!3d25.1206151!4d121.4605922?hl=zh-TW",關渡碼頭,4.3,渡輪碼頭,171.0,NaN,112台北市北投區,Plus Code: 4FC6+66 北投區 台北市,0,0,...,51-200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",23.546162,120.6402133
2,"https://www.google.com.tw/maps/place/%E5%A4%A7%E4%BD%B3%E7%A2%BC%E9%A0%AD/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442ac001be19b15:0xf9bc92e1a579e2f9!8m2!3d25.0761837!4d121.5374097?hl=zh-TW",大佳碼頭,4.3,海港,10.0,NaN,10491台北市中山區,NaN,0,0,...,0-50,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",23.546162,120.6402133
3,"https://www.google.com.tw/maps/place/%E9%87%91%E8%89%B2%E6%B0%B4%E5%B2%B8%E8%87%AA%E8%A1%8C%E8%BB%8A%E9%81%93/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442af71de435773:0xa9ffd262572b4f3!8m2!3d25.125148!4d121.461198?hl=zh-TW",金色水岸自行車道,4.3,單車公園,255.0,NaN,251新北市淡水區,Plus Code: 4FG6+3F 淡水區 新北市,0,0,...,201-500,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",23.546162,120.6402133
4,"https://www.google.com.tw/maps/place/%E9%9B%99%E6%BA%AA%E6%B2%B3%E6%BF%B1%E5%85%AC%E5%9C%92/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442ae97fd93f2bb:0xd37a39b3faa3df90!8m2!3d25.099919!4d121.528024?hl=zh-TW",雙溪河濱公園,4.2,公園,4849.0,NaN,111台北市士林區福林路,Plus Code: 3GXH+X6 士林區 台北市,0,0,...,3001 up,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",23.546162,120.6402133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,https://www.google.com.tw/maps/place/%E5%9C%93%E8%A6%BA%E7%80%91%E5%B8%83/data=!4m7!3m6!1s0x3442ad204ede3b97:0x368a61ba580d6149!8m2!3d25.0975497!4d121.5945882!16s%2Fg%2F12hnbwm5j!19sChIJlzveTiCtQjQRSWENWLphijY?authuser=0&hl=zh-TW&rclk=1,圓覺瀑布,4.3,景點,1561.0,NaN,114台北市內湖區大湖街131巷59號,Plus Code: 3HXV+2R 內湖區 台北市,0,0,...,1001-2000,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",25.0975497,121.5945882
343,https://www.google.com.tw/maps/place/%E8%87%BA%E5%8C%97%E5%B8%82%E6%94%BF%E5%BA%9C/data=!4m7!3m6!1s0x3442aba4c7b541bd:0x64bb871eceec226d!8m2!3d25.0374508!4d121.5638224!16s%2Fg%2F11t9_gdjcy!19sChIJvUG1x6SrQjQRbSLszh6Hu2Q?authuser=0&hl=zh-TW&rclk=1,臺北市政府,3.0,市政府辦公室,25.0,NaN,"110台北市信義區市府路 Taipei City Hall, No. 1",Plus Code: 2HP7+XG 信義區 台北市,0,0,...,0-50,"[0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",25.0374508,121.5638224
344,https://www.google.com.tw/maps/place/%E5%8F%B0%E5%8C%97%E5%B8%82%E7%AB%8B%E5%A4%A9%E6%AF%8D%E6%A3%92%E7%90%83%E5%A0%B4/data=!4m7!3m6!1s0x3442ae81a030469b:0x1f65196e5aa1053c!8m2!3d25.1134462!4d121.5329249!16s%2Fm%2F026_k17!19sChIJm0YwoIGuQjQRPAWhWm4ZZR8?authuser=0&hl=zh-TW&rclk=1,台北市立天母棒球場,4.3,棒球場,2001.0,NaN,111台北市士林區忠誠路二段77號,Plus Code: 4G7M+95 士林區 台北市,0,0,...,2001-3000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",25.1134462,121.5329249
345,https://www.google.com.tw/maps/place/%E6%B9%96%E5%B1%B1%E5%85%AD%E8%99%9F%E5%85%AC%E5%9C%92/data=!4m7!3m6!1s0x3442aceb1ab47861:0x31722c9764066443!8m2!3d25.0830998!4d121.6019904!16s%2Fg%2F11fxb5s2m3!19sChIJYXi0GuusQjQRQ2QGZJcscjE?authuser=0&hl=zh-TW&rclk=1,湖山六號公園,4.4,公園,342.0,NaN,114台北市內湖區大湖街166巷30號,Plus Code: 3JM2+6Q 內湖區 台北市,0,0,...,201-500,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",25.0830998,121.6019904
346,https://www.google.com.tw/maps/place/%E6%9E%8B%E9%9A%99%E6%95%99%E6%9C%83%E5%8E%9F%E5%9D%80/data=!4m7!3m6!1s0x3442a9534f364dbb:0xf858290b39e05b53!8m2!3d25.0650043!4d121.5097477!16s%2Fg%2F11s927n9pj!19sChIJu002T1OpQjQRU1vgOQspWPg?authuser=0&hl=zh-TW&rclk=1,枋隙教會原址,5.0,歷史地標,11.0,NaN,103台北市大同區迪化街二段67號,Plus Code: 3G85+2V 大同區 台北市,0,0,...,0-50,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0]",25.0650043,121.5097477

## 清整完存成csv

In [17]:
df.to_csv('attraction_info_final.csv',index=None)

In [18]:
dfClass = pd.read_csv("景點類別 - 工作表2.csv")
dfClass.head(2)

,Unnamed: 0,google_url,place_name,total_rating,Unnamed: 4,total_reviews,cost,address,district,eat_in,...,opening_hour,website,phone,close,place_acquisition_date,file_name_1,分類,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,0,"https://www.google.com.tw/maps/place/%E5%A4%A7%E7%A8%BB%E5%9F%95%E7%A2%BC%E9%A0%AD%E8%B2%A8%E6%AB%83%E5%B8%82%E9%9B%86/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442a91146436021:0x6dafa0aee6af38bf!8m2!3d25.0561339!4d121.5074245?hl=zh-TW",大稻埕碼頭貨櫃市集,4.5,NaN,1834.0,NaN,103台北市大同區,Plus Code: 3G44+FX 大同區 台北市,0,...,星期三、16:00 到 00:00; 星期四、16:00 到 00:00; 星期五、16:00 到 00:00; 星期六、12:00 到 00:00; 星期日、12:00 到 00:00; 星期一、16:00 到 00:00; 星期二、16:00 到 00:00. 隱藏本週營業時間,https://www.facebook.com/M.DaDaoCheng/,NaN,NaN,2022-11-23,a0,渡輪碼頭,NaN,NaN,渡輪碼頭
1,1,"https://www.google.com.tw/maps/place/%E9%97%9C%E6%B8%A1%E7%A2%BC%E9%A0%AD/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442af6e97a707ef:0xd2c2fd02bda75f14!8m2!3d25.1206151!4d121.4605922?hl=zh-TW",關渡碼頭,4.3,NaN,171.0,NaN,112台北市北投區,Plus Code: 4FC6+66 北投區 台北市,0,...,NaN,http://taiwan.net.tw/m1.aspx?sNo=0001090&id=34173,NaN,NaN,2022-11-23,a1,渡輪碼頭,NaN,NaN,公園

In [19]:
pd.set_option("display.max_columns",40)

In [20]:
dfClass[["place_name","分類"]]

    place_name     分類
0    大稻埕碼頭貨櫃市集   渡輪碼頭
1         關渡碼頭   渡輪碼頭
2         大佳碼頭   渡輪碼頭
3     金色水岸自行車道    NaN
4       雙溪河濱公園     公園
..         ...    ...
342       圓覺瀑布    風景區
343      臺北市政府    NaN
344  台北市立天母棒球場     公園
345     湖山六號公園     公園
346     枋隙教會原址  寺廟/教堂

[347 rows x 2 columns]

In [21]:
dfClass1 = dfClass.loc[:,"分類"]
dfClass1

0       渡輪碼頭
1       渡輪碼頭
2       渡輪碼頭
3        NaN
4         公園
       ...
342      風景區
343      NaN
344       公園
345       公園
346    寺廟/教堂
Name: 分類, Length: 347, dtype: object

In [22]:
df["New place_category"] = dfClass1

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 347 entries, 0 to 346
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   google_url              347 non-null    object
 1   place_name              347 non-null    object
 2   total_rating            347 non-null    float64
 3   place_category          347 non-null    object
 4   total_reviews           347 non-null    float64
 5   cost                    48 non-null     object
 6   address                 347 non-null    object
 7   district                344 non-null    object
 8   eat_in                  347 non-null    int64
 9   to_go_1                 347 non-null    int64
 10  to_go_2                 347 non-null    int64
 11  delivery                347 non-null    int64
 12  opening_hour            288 non-null    object
 13  website                 294 non-null    object
 14  phone                   273 non-null    object
 15  close                   0 non-null      float64
 16  place_acquisition_date  347 non-null    object
 17  file_name_1             347 non-null    object
 18  New district            344 non-null    object
 19  New Rating              347 non-null    int64
 20  New review              347 non-null    object
 21  Monday                  347 non-null    object
 22  Tuesday                 347 non-null    object
 23  Wednesday               347 non-null    object
 24  Thursday                347 non-null    object
 25  Friday                  347 non-null    object
 26  Saturday                347 non-null    object
 27  Sunday                  347 non-null    object
 28  latitude                347 non-null    object
 29  longitude               347 non-null    object
 30  New place_category      295 non-null    object
dtypes: float64(3), int64(5), object(23)
memory usage: 84.2+ KB

In [24]:
df = df[~df["New place_category"].isna()]

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 295 entries, 0 to 346
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   google_url              295 non-null    object
 1   place_name              295 non-null    object
 2   total_rating            295 non-null    float64
 3   place_category          295 non-null    object
 4   total_reviews           295 non-null    float64
 5   cost                    40 non-null     object
 6   address                 295 non-null    object
 7   district                292 non-null    object
 8   eat_in                  295 non-null    int64
 9   to_go_1                 295 non-null    int64
 10  to_go_2                 295 non-null    int64
 11  delivery                295 non-null    int64
 12  opening_hour            244 non-null    object
 13  website                 255 non-null    object
 14  phone                   235 non-null    object
 15  close                   0 non-null      float64
 16  place_acquisition_date  295 non-null    object
 17  file_name_1             295 non-null    object
 18  New district            292 non-null    object
 19  New Rating              295 non-null    int64
 20  New review              295 non-null    object
 21  Monday                  295 non-null    object
 22  Tuesday                 295 non-null    object
 23  Wednesday               295 non-null    object
 24  Thursday                295 non-null    object
 25  Friday                  295 non-null    object
 26  Saturday                295 non-null    object
 27  Sunday                  295 non-null    object
 28  latitude                295 non-null    object
 29  longitude               295 non-null    object
 30  New place_category      295 non-null    object
dtypes: float64(3), int64(5), object(23)
memory usage: 73.8+ KB

In [26]:
df[df["New district"].isna()]

,google_url,place_name,total_rating,place_category,total_reviews,cost,address,district,eat_in,to_go_1,to_go_2,delivery,opening_hour,website,phone,close,place_acquisition_date,file_name_1,New district,New Rating,New review,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,latitude,longitude,New place_category
2,"https://www.google.com.tw/maps/place/%E5%A4%A7%E4%BD%B3%E7%A2%BC%E9%A0%AD/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442ac001be19b15:0xf9bc92e1a579e2f9!8m2!3d25.0761837!4d121.5374097?hl=zh-TW",大佳碼頭,4.3,海港,10.0,NaN,10491台北市中山區,NaN,0,0,0,0,NaN,NaN,NaN,NaN,2022-11-23,a2,NaN,4,0-50,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",23.546162,120.6402133,渡輪碼頭
75,"https://www.google.com.tw/maps/place/%E5%BD%A9%E8%99%B9%E7%A2%BC%E9%A0%AD/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442ab9bcf268111:0xea9a66c6a5de9f33!8m2!3d25.0514336!4d121.5749295?hl=zh-TW",彩虹碼頭,4.2,海港,14.0,NaN,105台北市松山區,NaN,0,0,0,0,NaN,NaN,NaN,NaN,2022-11-23,a75,NaN,4,0-50,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",23.546162,120.6402133,渡輪碼頭
171,"https://www.google.com.tw/maps/place/%E5%A4%A2%E5%B9%BB%E6%B9%96/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442b26d315ff96f:0x83c0b5426e02c043!8m2!3d25.1667829!4d121.5602805?hl=zh-TW",夢幻湖,4.4,季節性湖泊,132.0,NaN,112台北市北投區,NaN,0,0,0,0,NaN,NaN,NaN,NaN,2022-11-23,a171,NaN,4,51-200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",23.546162,120.6402133,風景區

In [27]:
df.loc[2,"New district"] = "中山區"
df.loc[75,"New district"] = "松山區"
df.loc[171,"New district"] = "北投區"

In [28]:
df[df["New district"].isna()]

Empty DataFrame
Columns: [google_url, place_name, total_rating, place_category, total_reviews, cost, address, district, eat_in, to_go_1, to_go_2, delivery, opening_hour, website, phone, close, place_acquisition_date, file_name_1, New district, New Rating, New review, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, latitude, longitude, New place_category]
Index: []

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 295 entries, 0 to 346
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   google_url              295 non-null    object
 1   place_name              295 non-null    object
 2   total_rating            295 non-null    float64
 3   place_category          295 non-null    object
 4   total_reviews           295 non-null    float64
 5   cost                    40 non-null     object
 6   address                 295 non-null    object
 7   district                292 non-null    object
 8   eat_in                  295 non-null    int64
 9   to_go_1                 295 non-null    int64
 10  to_go_2                 295 non-null    int64
 11  delivery                295 non-null    int64
 12  opening_hour            244 non-null    object
 13  website                 255 non-null    object
 14  phone                   235 non-null    object
 15  close                   0 non-null      float64
 16  place_acquisition_date  295 non-null    object
 17  file_name_1             295 non-null    object
 18  New district            295 non-null    object
 19  New Rating              295 non-null    int64
 20  New review              295 non-null    object
 21  Monday                  295 non-null    object
 22  Tuesday                 295 non-null    object
 23  Wednesday               295 non-null    object
 24  Thursday                295 non-null    object
 25  Friday                  295 non-null    object
 26  Saturday                295 non-null    object
 27  Sunday                  295 non-null    object
 28  latitude                295 non-null    object
 29  longitude               295 non-null    object
 30  New place_category      295 non-null    object
dtypes: float64(3), int64(5), object(23)
memory usage: 81.9+ KB

In [30]:
df[df["total_reviews"]<30]

,google_url,place_name,total_rating,place_category,total_reviews,cost,address,district,eat_in,to_go_1,to_go_2,delivery,opening_hour,website,phone,close,place_acquisition_date,file_name_1,New district,New Rating,New review,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,latitude,longitude,New place_category
2,"https://www.google.com.tw/maps/place/%E5%A4%A7%E4%BD%B3%E7%A2%BC%E9%A0%AD/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442ac001be19b15:0xf9bc92e1a579e2f9!8m2!3d25.0761837!4d121.5374097?hl=zh-TW",大佳碼頭,4.3,海港,10.0,NaN,10491台北市中山區,NaN,0,0,0,0,NaN,NaN,NaN,NaN,2022-11-23,a2,中山區,4,0-50,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",23.546162,120.6402133,渡輪碼頭
75,"https://www.google.com.tw/maps/place/%E5%BD%A9%E8%99%B9%E7%A2%BC%E9%A0%AD/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442ab9bcf268111:0xea9a66c6a5de9f33!8m2!3d25.0514336!4d121.5749295?hl=zh-TW",彩虹碼頭,4.2,海港,14.0,NaN,105台北市松山區,NaN,0,0,0,0,NaN,NaN,NaN,NaN,2022-11-23,a75,松山區,4,0-50,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",23.546162,120.6402133,渡輪碼頭
127,"https://www.google.com.tw/maps/place/%E5%AD%B8%E6%B5%B7%E6%9B%B8%E9%99%A2/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442a9ac133696ad:0x33f14dfe7624be9d!8m2!3d25.0363676!4d121.495475?hl=zh-TW",學海書院,3.9,寺廟,15.0,NaN,108台北市萬華區環河南路二段93號,Plus Code: 2FPW+G7 萬華區 台北市,0,0,0,0,NaN,https://www.travel.taipei/zh-tw/attraction/details/397,NaN,NaN,2022-11-23,a127,萬華區,4,0-50,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",23.546162,120.6402133,寺廟/教堂
129,"https://www.google.com.tw/maps/place/%E9%8C%A6%E7%94%BA%E6%97%A5%E5%BC%8F%E5%AE%BF%E8%88%8D%E7%BE%A4-%E6%AD%B7%E5%8F%B2%E5%BB%BA%E7%AF%89/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442a984f0dabdeb:0xc6268dd4c549f354!8m2!3d25.027748!4d121.5280304?hl=zh-TW",錦町日式宿舍群-歷史建築,4.0,歷史建築,11.0,NaN,台北市大安區,Plus Code: 2GHH+46 大安區 台北市,0,0,0,0,NaN,https://nchdb.boch.gov.tw/assets/advanceSearch/historicalBuilding/20070530000002,NaN,NaN,2022-11-23,a129,大安區,4,0-50,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",23.546162,120.6402133,歷史景點
201,"https://www.google.com.tw/maps/place/%E7%A1%AB%E7%A3%BA%E8%B0%B7%EF%BD%9C%E5%A4%A7%E7%A3%BA%E5%98%B4/@23.546162,120.6402133,8z/data=!4m5!3m4!1s0x3442ae132975ac3f:0x6f3afedb9f0f5593!8m2!3d25.1427048!4d121.5225381?hl=zh-TW",硫磺谷｜大磺嘴,4.3,景點,26.0,NaN,112台北市北投區泉源路143-144號,Plus Code: 4GVF+32 北投區 台北市,0,0,0,0,星期三、24 小時營業; 星期四、24 小時營業; 星期五、24 小時營業; 星期六、24 小時營業; 星期日、24 小時營業; 星期一、24 小時營業; 星期二、24 小時營業. 隱藏本週營業時間,http://btdo.gov.taipei/ct.asp?xItem=18049731&ctNode=51503&mp=124081,02 2891 2105,NaN,2022-11-23,a201,北投區,4,0-50,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",23.546162,120.6402133,風景區
298,https://www.google.com.tw/maps/place/%E5%9F%BA%E9%9A%86%E6%B2%B3%E8%87%AA%E8%A1%8C%E8%BB%8A%E9%81%93/data=!4m7!3m6!1s0x345d51f5ffc588d9:0x5115dce81c61fcb6!8m2!3d25.1008909!4d121.7196783!16s%2Fg%2F11dz19s81c!19sChIJ2YjF__VRXTQRtvxhHOjcFVE?authuser=0&hl=zh-TW&rclk=1,基隆河自行車道,4.5,單車公園,26.0,NaN,206基隆市七堵區八德路2-16號,Plus Code: 4P29+9V 七堵區 基隆市,0,0,0,0,星期三、24 小時營業; 星期四、24 小時營業; 星期五、24 小時營業; 星期六、24 小時營業; 星期日、24 小時營業; 星期一、24 小時營業; 星期二、24 小時營業. 隱藏本週營業時間,NaN,NaN,NaN,2022-11-23,a300,七堵區,4,0-50,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",25.1008909,121.7196783,公園
306,https://www.google.com.tw/maps/place/%E5%8F%B0%E5%8C%97%E5%B8%82%E5%8F%A4%E4%BA%AD%E6%B2%B3%E6%BF%B1%E5%85%AC%E5%9C%92/data=!4m7!3m6!1s0x3442a98aa5ebe3cd:0x1e04851f084a217!8m2!3d25.0206167!4d121.5200644!16s%2Fg%2F11b7x1y_n7!19sChIJzePrpYqpQjQRF6KE8FFI4AE?authuser=0&hl=zh-TW&rclk=1,台北市古亭河濱公園,4.7,公園,12.0,NaN,100台北市中正區同安街109巷10號,Plus Code: 2GCC+62 中正區 台北市,0,0,0,0,星期三、24 小時營業; 星期四、24 小時營業; 星期五、24 小時營業; 星期六、24 小時營業; 星期日、24 小時營業; 星期一、24 小時營業; 星期二、24 小時營業. 隱藏本週營業時間,https://heo.gov.taipei/News_Content.aspx?n=E65DBD99C91AEAC4&sms=3A0FD6D3764BFBA7&s=32A53CBA0EEBE107,NaN,NaN,2022-11-23,a309,中正區,5,0-50,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",25.0206167,121.5200644,公園
311,https://www.google.com.tw/maps/place/%E5%8F%B0%E5%8C%97%E5%B8%82%E5%A3%AB%E6%9E%97%E5%A4%9C%E5%B8%82%E5%9C%8B%E9%9A%9B%E8%A7%80%E5%85%89%E7%99%BC%E5%B1%95%E5%8D%94%E6%9C%83/data=!4m7!3m6!1s0x3442af8b2a24011b:0x2c8dd45c980fa9ef!8m2!3d25.0976294!4d121.5264336!16s%2Fg%2F11jpqw6pxx!19sChIJGwEkKouvQjQR76kPmFzUjSw?authuser=0&hl=zh-TW&rclk=1,台北市士林夜市國際觀光發展協會,4.6,夜市,16.0,NaN,111台北市士林區中山北路五段699巷20號,Plus Code: 3GXG+3H 士林區 台北市,0,0,0,0,星期三、17:00 到 23:30; 星期四、17:00 到 23:30; 星期五、17:00 到 23:00; 星期六、17:00 到 23:00; 星期日、17:00 到 23:30; 星期一、17:00 到 23:30; 星期二、17:00 到 23:30. 隱藏本週營業時間,NaN,02 2833 2188,NaN,2022-11-23,a314,士林區,5,0-50,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0]",25.0976294,121.5264336,夜市
346,https://www.google.com.tw/maps/place/%E6%9E%8B%E9%9A%99%E6%95%99%E6%9C%83%E5%8E%9F%E5%9D%80/data=!4m7!3m6!1s0x3442a9534f364dbb:0xf858290b39e05b53!8m2!3d25.0650043!4d121.5097477!16s%2Fg%2F11s927n9pj!19sChIJu002T1OpQjQRU1vgOQspWPg?authuser=0&hl=zh-TW&rclk=1,枋隙教會原址,5.0,歷史地標,11.0,NaN,103台北市大同區迪化街二段67號,Plus Code: 3G85+2V 大同區 台北市,0,0,0,0,星期三、09:00 到 16:00; 星期四、09:00 到 16:00; 星期五、09:00 到 16:00; 星期六、09:00 到 21:00; 星期日、09:00 到 17:00; 星期一、休息; 星期二、休息. 隱藏本週營業時間,https://sites.google.com/view/pctc0267/%E9%97%9C%E6%96%BC/history,02 2597 4784,NaN,2022-11-23,a349,大同區,5,0-50,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 0]",25.0650043,121.5097477,寺廟/教堂

In [31]:
df["place_name"][df["New place_category"]=="夜市"]

144                                        臺北華西街夜市
145                                        饒河街觀光夜市
153    台北市臨江街觀光夜市｜通化街夜市 Taiwan Taipei Night Market
154                                          雙城街夜市
155                                        廣州街觀光夜市
156                                        梧州街觀光夜市
157                                           遼寧夜市
158                                          大龍街夜市
213                                         台北公館夜市
311                                台北市士林夜市國際觀光發展協會
316                                           寧夏夜市
317                                           景美夜市
318                                          南機場夜市
319                                           西昌夜市
320                                           延三夜市
341                                        737巷美食街
Name: place_name, dtype: object

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 295 entries, 0 to 346
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   google_url              295 non-null    object
 1   place_name              295 non-null    object
 2   total_rating            295 non-null    float64
 3   place_category          295 non-null    object
 4   total_reviews           295 non-null    float64
 5   cost                    40 non-null     object
 6   address                 295 non-null    object
 7   district                292 non-null    object
 8   eat_in                  295 non-null    int64
 9   to_go_1                 295 non-null    int64
 10  to_go_2                 295 non-null    int64
 11  delivery                295 non-null    int64
 12  opening_hour            244 non-null    object
 13  website                 255 non-null    object
 14  phone                   235 non-null    object
 15  close                   0 non-null      float64
 16  place_acquisition_date  295 non-null    object
 17  file_name_1             295 non-null    object
 18  New district            295 non-null    object
 19  New Rating              295 non-null    int64
 20  New review              295 non-null    object
 21  Monday                  295 non-null    object
 22  Tuesday                 295 non-null    object
 23  Wednesday               295 non-null    object
 24  Thursday                295 non-null    object
 25  Friday                  295 non-null    object
 26  Saturday                295 non-null    object
 27  Sunday                  295 non-null    object
 28  latitude                295 non-null    object
 29  longitude               295 non-null    object
 30  New place_category      295 non-null    object
dtypes: float64(3), int64(5), object(23)
memory usage: 81.9+ KB

In [33]:
pd.set_option("display.max_colwidth",10)

In [34]:
pd.set_option("display.max_columns",10)

In [35]:
dfmarket = pd.read_csv("night_market_place_info.csv",header=None)
dfmarket

,0,1,2,3,4,...,14,15,16,17,18
0,0,https:...,士林夜市,4.0,夜市,...,https:...,02 28...,NaN,2022-1...,a350
1,0,https:...,師大夜市,4.0,夜市,...,https:...,0901 ...,NaN,2022-1...,a351
2,0,https:...,西門町徒步區,4.3,旅遊景點,...,NaN,02 23...,NaN,2022-1...,a352
3,0,https:...,永康街商圈,4.2,旅遊景點,...,http:/...,02 23...,NaN,2022-1...,a353

In [37]:
dfmarket = dfmarket.iloc[:,1:]
dfmarket

,1,2,3,4,5,...,14,15,16,17,18
0,https:...,士林夜市,4.0,夜市,7472,...,https:...,02 28...,NaN,2022-1...,a350
1,https:...,師大夜市,4.0,夜市,17628,...,https:...,0901 ...,NaN,2022-1...,a351
2,https:...,西門町徒步區,4.3,旅遊景點,8425,...,NaN,02 23...,NaN,2022-1...,a352
3,https:...,永康街商圈,4.2,旅遊景點,663,...,http:/...,02 23...,NaN,2022-1...,a353

In [38]:
df

,google_url,place_name,total_rating,place_category,total_reviews,...,Saturday,Sunday,latitude,longitude,New place_category
0,https:...,大稻埕碼頭貨櫃市集,4.5,旅遊景點,1834.0,...,"[0.0, ...","[0.0, ...",23.546162,120.64...,渡輪碼頭
1,https:...,關渡碼頭,4.3,渡輪碼頭,171.0,...,"[0, 0,...","[0, 0,...",23.546162,120.64...,渡輪碼頭
2,https:...,大佳碼頭,4.3,海港,10.0,...,"[0, 0,...","[0, 0,...",23.546162,120.64...,渡輪碼頭
4,https:...,雙溪河濱公園,4.2,公園,4849.0,...,"[1, 1,...","[1, 1,...",23.546162,120.64...,公園
5,https:...,天母古道親山步道,4.4,行山徑,3471.0,...,"[1, 1,...","[1, 1,...",23.546162,120.64...,風景區
...,...,...,...,...,...,...,...,...,...,...,...
341,https:...,737巷美食街,4.1,夜市,7681.0,...,"[0, 0,...","[0, 0,...",25.079738,121.57...,夜市
342,https:...,圓覺瀑布,4.3,景點,1561.0,...,"[1, 1,...","[1, 1,...",25.097...,121.59...,風景區
344,https:...,台北市立天母棒球場,4.3,棒球場,2001.0,...,"[0, 0,...","[0, 0,...",25.113...,121.53...,公園
345,https:...,湖山六號公園,4.4,公園,342.0,...,"[1, 1,...","[1, 1,...",25.083...,121.60...,公園
346,https:...,枋隙教會原址,5.0,歷史地標,11.0,...,"[0, 0,...","[0, 0,...",25.065...,121.50...,寺廟/教堂

In [50]:
a = df.columns.to_list()[:18]
dfmarket.columns = a

In [51]:
dfmarket

,google_url,place_name,total_rating,place_category,total_reviews,...,website,phone,close,place_acquisition_date,file_name_1
0,https:...,士林夜市,4.0,夜市,7472,...,https:...,02 28...,NaN,2022-1...,a350
1,https:...,師大夜市,4.0,夜市,17628,...,https:...,0901 ...,NaN,2022-1...,a351
2,https:...,西門町徒步區,4.3,旅遊景點,8425,...,NaN,02 23...,NaN,2022-1...,a352
3,https:...,永康街商圈,4.2,旅遊景點,663,...,http:/...,02 23...,NaN,2022-1...,a353

In [52]:
df = pd.concat([df,dfmarket])
df

,google_url,place_name,total_rating,place_category,total_reviews,...,Saturday,Sunday,latitude,longitude,New place_category
0,https:...,大稻埕碼頭貨櫃市集,4.5,旅遊景點,1834.0,...,"[0.0, ...","[0.0, ...",23.546162,120.64...,渡輪碼頭
1,https:...,關渡碼頭,4.3,渡輪碼頭,171.0,...,"[0, 0,...","[0, 0,...",23.546162,120.64...,渡輪碼頭
2,https:...,大佳碼頭,4.3,海港,10.0,...,"[0, 0,...","[0, 0,...",23.546162,120.64...,渡輪碼頭
4,https:...,雙溪河濱公園,4.2,公園,4849.0,...,"[1, 1,...","[1, 1,...",23.546162,120.64...,公園
5,https:...,天母古道親山步道,4.4,行山徑,3471.0,...,"[1, 1,...","[1, 1,...",23.546162,120.64...,風景區
...,...,...,...,...,...,...,...,...,...,...,...
346,https:...,枋隙教會原址,5.0,歷史地標,11.0,...,"[0, 0,...","[0, 0,...",25.065...,121.50...,寺廟/教堂
0,https:...,士林夜市,4.0,夜市,7472.0,...,NaN,NaN,NaN,NaN,NaN
1,https:...,師大夜市,4.0,夜市,17628.0,...,NaN,NaN,NaN,NaN,NaN
2,https:...,西門町徒步區,4.3,旅遊景點,8425.0,...,NaN,NaN,NaN,NaN,NaN
3,https:...,永康街商圈,4.2,旅遊景點,663.0,...,NaN,NaN,NaN,NaN,NaN

In [54]:
dfnightatt = pd.read_csv("night_attraction_place_info.csv",header=None)
dfnightatt = dfnightatt.iloc[:,1:]

In [55]:
dfnightatt

,1,2,3,4,5,...,14,15,16,17,18
0,https:...,文化大學後山情人坡,4.4,旅遊景點,2151,...,http:/...,02 28...,NaN,2022-1...,a354
1,https:...,樟山寺,4.4,佛寺,2073,...,http:/...,02 29...,NaN,2022-1...,a355
2,https:...,象山六巨石觀景台,4.6,觀景台,2016,...,NaN,02 27...,NaN,2022-1...,a356
3,https:...,內湖 碧山巖,4.6,觀景台,1543,...,https:...,02 27...,NaN,2022-1...,a357
4,https:...,劍南山夜景,4.1,景點,2046,...,NaN,NaN,NaN,2022-1...,a358
5,https:...,四季長廊觀景台,4.6,旅遊景點,1822,...,NaN,NaN,NaN,2022-1...,a359

In [56]:
dfnightatt.columns = a
dfnightatt

,google_url,place_name,total_rating,place_category,total_reviews,...,website,phone,close,place_acquisition_date,file_name_1
0,https:...,文化大學後山情人坡,4.4,旅遊景點,2151,...,http:/...,02 28...,NaN,2022-1...,a354
1,https:...,樟山寺,4.4,佛寺,2073,...,http:/...,02 29...,NaN,2022-1...,a355
2,https:...,象山六巨石觀景台,4.6,觀景台,2016,...,NaN,02 27...,NaN,2022-1...,a356
3,https:...,內湖 碧山巖,4.6,觀景台,1543,...,https:...,02 27...,NaN,2022-1...,a357
4,https:...,劍南山夜景,4.1,景點,2046,...,NaN,NaN,NaN,2022-1...,a358
5,https:...,四季長廊觀景台,4.6,旅遊景點,1822,...,NaN,NaN,NaN,2022-1...,a359

In [59]:
df = pd.concat([df,dfnightatt])
df

,google_url,place_name,total_rating,place_category,total_reviews,cost,address,district,eat_in,to_go_1,to_go_2,delivery,opening_hour,website,phone,close,place_acquisition_date,file_name_1,New district,New Rating,New review,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,latitude,longitude,New place_category
0,https:...,大稻埕碼頭貨櫃市集,4.5,旅遊景點,1834.0,NaN,103台北...,Plus C...,0,0,0,0,星期三、16...,https:...,NaN,NaN,2022-1...,a0,大同區,4.0,1001-2000,"[0.0, ...","[0.0, ...","[0.0, ...","[0.0, ...","[0.0, ...","[0.0, ...","[0.0, ...",23.546162,120.64...,渡輪碼頭
1,https:...,關渡碼頭,4.3,渡輪碼頭,171.0,NaN,112台北...,Plus C...,0,0,0,0,NaN,http:/...,NaN,NaN,2022-1...,a1,北投區,4.0,51-200,"[0, 0,...","[0, 0,...","[0, 0,...","[0, 0,...","[0, 0,...","[0, 0,...","[0, 0,...",23.546162,120.64...,渡輪碼頭
2,https:...,大佳碼頭,4.3,海港,10.0,NaN,10491...,NaN,0,0,0,0,NaN,NaN,NaN,NaN,2022-1...,a2,中山區,4.0,0-50,"[0, 0,...","[0, 0,...","[0, 0,...","[0, 0,...","[0, 0,...","[0, 0,...","[0, 0,...",23.546162,120.64...,渡輪碼頭
4,https:...,雙溪河濱公園,4.2,公園,4849.0,NaN,111台北...,Plus C...,0,0,0,0,星期三、24...,https:...,NaN,NaN,2022-1...,a4,士林區,4.0,3001 up,"[1, 1,...","[1, 1,...","[1, 1,...","[1, 1,...","[1, 1,...","[1, 1,...","[1, 1,...",23.546162,120.64...,公園
5,https:...,天母古道親山步道,4.4,行山徑,3471.0,NaN,111台北...,Plus C...,0,0,0,0,星期三、24...,https:...,NaN,NaN,2022-1...,a5,士林區,4.0,3001 up,"[1, 1,...","[1, 1,...","[1, 1,...","[1, 1,...","[1, 1,...","[1, 1,...","[1, 1,...",23.546162,120.64...,風景區
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,https:...,樟山寺,4.4,佛寺,2073.0,NaN,116台北...,Plus C...,0,0,0,0,NaN,http:/...,02 29...,NaN,2022-1...,a355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https:...,象山六巨石觀景台,4.6,觀景台,2016.0,NaN,110台北...,Plus C...,0,0,0,0,星期一、24...,NaN,02 27...,NaN,2022-1...,a356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https:...,內湖 碧山巖,4.6,觀景台,1543.0,NaN,114台北...,Plus C...,0,0,0,0,星期一、06...,https:...,02 27...,NaN,2022-1...,a357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https:...,劍南山夜景,4.1,景點,2046.0,NaN,10491...,Plus C...,0,0,0,0,星期一、24...,NaN,NaN,NaN,2022-1...,a358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,https:...,四季長廊觀景台,4.6,旅遊景點,1822.0,NaN,112台北...,Plus C...,0,0,0,0,星期一、24...,NaN,NaN,NaN,2022-1...,a359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df.to_csv("attarction_info_final_1212.csv",index=None)

In [58]:
pd.set_option("display.max_columns",31)